export const TOGGLE_CHECKBOX_FILTER = 'TOGGLE_CHECKBOX_FILTER';
export const TOGGLE_FAVORITES_FILTER = 'TOGGLE_FAVORITES_FILTER';
export const UPDATE_INPUT_FILTER = 'UPDATE_INPUT_FILTER';
export const GET_NEXT_HITS = 'GET_NEXT_HITS';
export const SYNC_URL_PARAMS = 'SYNC_URL_PARAMS';
