export const SELECT_BOX_TO_BROWSE = 'SELECT_BOX_TO_BROWSE';
export const UNSELECT_BOX_TO_BROWSE = 'UNSELECT_BOX_TO_BROWSE';
export const SELECT_CELL_TO_BROWSE = 'SELECT_CELL_TO_BROWSE';
export const UNSELECT_CELL_TO_BROWSE = 'UNSELECT_CELL_TO_BROWSE';
