export const WINE_ADDITION_PROCESSING = 'WINE_ADDITION_PROCESSING';
export const WINE_ADDED = 'WINE_ADDED';
export const SET_CELLAR = 'SET_CELLAR';
export const SET_BASKET = 'SET_BASKET';
export const UPLOAD_PICTURE = 'UPLOAD_PICTURE';
export const RECEIVE_PICTURE_INFOS = 'RECEIVE_PICTURE_INFOS';
export const SELECT_BOX = 'SELECT_BOX';
export const UNSELECT_BOX = 'UNSELECT_BOX';
export const SELECT_CELL = 'SELECT_CELL';
export const UNSELECT_CELL = 'UNSELECT_CELL';
export const SELECT_NEXT_BOX = 'SELECT_NEXT_BOX';
export const RESET_UPLOAD = 'RESET_UPLOAD';

export const SET_ERROR_NOTIFICATION = 'SET_ERROR_NOTIFICATION';
export const SET_SUCCESS_NOTIFICATION = 'SET_SUCCESS_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
