export const WineFamilies = {
  0: 'Autre',
  1: 'Alsace Grand Cru Ollwiller',
  2: 'Alsace Grand Cru Osterberg',
  3: 'Alsace Grand Cru Pfersigberg',
  4: 'Alsace Grand Cru Pfingstberg',
  5: 'Alsace Grand Cru Praelatenberg',
  6: 'Alsace Grand Cru Rangen',
  7: 'Alsace Grand Cru Rosacker',
  8: 'Alsace Grand Cru Saering',
  9: 'Alsace Grand Cru Schlossberg',
  10: 'Alsace Grand Cru Schoenenbourg',
  11: 'Alsace Grand Cru Sommerberg',
  12: 'Alsace Grand Cru Sonnenglanz',
  13: 'Alsace Grand Cru Spiegel',
  14: 'Alsace Grand Cru Sporen',
  15: 'Alsace Grand Cru Steinert',
  16: 'Alsace Grand Cru Steingrubler',
  17: 'Alsace Grand Cru Steinklotz',
  18: 'Alsace Grand Cru Vorbourg',
  19: 'Alsace Grand Cru Wiebelsberg',
  20: 'Alsace Grand Cru Wineck-Schlossberg',
  21: 'Alsace Grand Cru Winzenberg',
  22: 'Alsace Grand Cru Zinnkoepflé',
  23: 'Alsace Grand Cru Zotzenberg',
  24: 'Anjou Blanc',
  25: 'Anjou Fines Bulles',
  26: 'Anjou Rouge',
  27: 'Anjou Villages Brissac',
  28: 'Anjou-Coteaux de la Loire',
  29: 'Anjou-Gamay',
  30: 'Anjou-Villages',
  31: 'Arbois',
  32: 'Auxey-Duresses',
  33: 'Bandol',
  34: 'Banyuls',
  35: 'Banyuls grand cru',
  36: 'Barsac',
  37: 'Bâtard-Montrachet',
  38: 'Béarn',
  39: 'Beaujolais',
  40: 'Beaujolais Blanc',
  41: 'Beaujolais Nouveau',
  42: 'Beaujolais-Villages',
  43: 'Beaumes-de-Venise',
  44: 'Beaune',
  45: 'Bellet',
  46: 'Bergerac',
  47: 'Bergerac sec',
  48: 'Bienvenues-Bâtard-Montrachet',
  49: 'Blagny',
  50: 'Blanquette de Limoux',
  51: 'Blanquette de Limoux méthode ancestrale',
  52: 'Blaye',
  53: 'Blaye Côtes de Bordeaux',
  54: 'Bonnes-Mares',
  55: 'Bonnezeaux',
  56: 'Bordeaux',
  57: 'Bordeaux Clairet',
  58: 'Bordeaux côtes de Francs',
  59: 'Bordeaux Haut-Benauge',
  60: 'Bordeaux rosé',
  61: 'Bordeaux sec',
  62: 'Bordeaux supérieur',
  63: 'Bourgogne',
  64: 'Bourgogne Aligoté',
  65: 'Bourgogne Chitry',
  66: 'Bourgogne Clairet',
  67: 'Bourgogne côte Chalonnaise',
  68: 'Bourgogne côte Saint-Jacques',
  69: 'Bourgogne côtes d\'Auxerre',
  70: 'Bourgogne côtes Du Couchois',
  71: 'Bourgogne Coulanges-la-Vineuse',
  72: 'Bourgogne Épineuil',
  73: 'Bourgogne Grand Ordinaire',
  74: 'Bourgogne Hautes-côtes de Beaune',
  75: 'Bourgogne Hautes-côtes de Nuits',
  76: 'Bourgogne La Chapelle Notre-Dame',
  77: 'Bourgogne Le Chapitre',
  78: 'Bourgogne Montrecul',
  79: 'Bourgogne Mousseux',
  80: 'Bourgogne Passe-tout-grain',
  81: 'Bourgogne Tonnerre',
  82: 'Bourgogne Vézelay',
  83: 'Bourgueil',
  84: 'Bouzeron',
  85: 'Brouilly',
  86: 'Brulhois',
  87: 'Bugey',
  88: 'Buzet',
  89: 'Cabardès',
  90: 'Cabernet d \'Anjou',
  91: 'Cabernet de Saumur',
  92: 'Cadillac',
  93: 'Cadillac Côtes de Bordeaux',
  94: 'Cahors',
  95: 'Canon-Fronsac',
  96: 'Cassis',
  97: 'Castillon Côtes de Bordeaux',
  98: 'Cerons',
  99: 'Chablis',
  100: 'Chablis Grand Cru',
  101: 'Chablis Premier Cru',
  102: 'Chambertin',
  103: 'Chambertin-Clos-de-Bèze',
  104: 'Chambolle-Musigny',
  105: 'Champagne',
  106: 'Chapelle-Chambertin',
  107: 'Charlemagne',
  108: 'Charmes-Chambertin',
  109: 'Chassagne-Montrachet',
  110: 'Château Grillet',
  111: 'Château-Chalon',
  112: 'Châteaumeillant',
  113: 'Châteauneuf-du-Pape',
  114: 'Châtillon-en-Diois',
  115: 'Chaume',
  116: 'Chénas',
  117: 'Chevalier-Montrachet',
  118: 'Cheverny',
  119: 'Chinon',
  120: 'Chiroubles',
  121: 'Chorey-les-Beaune',
  122: 'Clairette de Bellegarde',
  123: 'Clairette de Die',
  124: 'Clairette du Languedoc',
  125: 'Clos de la Roche',
  126: 'Clos de Tart',
  127: 'Clos de Vougeot',
  128: 'Clos des Lambrays',
  129: 'Clos Saint-Denis',
  130: 'Collioure',
  131: 'Condrieu',
  132: 'Corbières',
  133: 'Corbières Boutenac',
  134: 'Cornas',
  135: 'Corse',
  136: 'Corse Calvi',
  137: 'Corse Coteaux du Cap Corse',
  138: 'Corse Figari',
  139: 'Corse Porto Vecchio',
  140: 'Corse Sartène',
  141: 'Corton',
  142: 'Corton-Charlemagne',
  143: 'Costières de NÃ®mes',
  144: 'Côte de Beaune',
  145: 'Côte de Beaune-Villages',
  146: 'Côte de Brouilly',
  147: 'Côte de Nuits-Villages',
  148: 'Côte roannaise',
  149: 'Côte-Rôtie',
  150: 'Coteaux Bourguignons',
  151: 'Coteaux Champenois',
  152: 'Coteaux d\'Aix-en-Provence',
  153: 'Coteaux d\'Ancenis',
  154: 'Coteaux de Die',
  155: 'Coteaux de l\'Aubance',
  156: 'Coteaux de Pierrevert-AOVDQS',
  157: 'Coteaux de Saumur',
  158: 'Coteaux du Giennois',
  159: 'Coteaux du Languedoc',
  160: 'Coteaux du Loir',
  161: 'Coteaux du Lyonnais',
  162: 'Coteaux du Quercy-AOVDQS',
  163: 'Coteaux du Tricastin',
  164: 'Coteaux du Vendômois',
  165: 'Coteaux Varois en Provence',
  166: 'Coteaux-du-Layon',
  167: 'Coteaux du Layon Saint Aubin',
  168: 'Côtes d\'Auvergne',
  169: 'Côtes de Bergerac',
  170: 'Côtes de Bordeaux',
  171: 'Côtes de Bordeaux Saint-Macaire',
  172: 'Côtes de Bourg',
  173: 'Côtes de Castillon',
  174: 'Côtes de Duras',
  175: 'Côtes de Francs',
  176: 'Côtes de la Malepère-AOVDQS',
  177: 'Côtes de Millau-AOVDQS',
  178: 'Côtes de Montravel',
  179: 'Côtes de Provence',
  180: 'Côtes de Provence Fréjus',
  181: 'Côtes de Provence Sainte-Victoire',
  182: 'Côtes de Saint-Mont-AOVDQS',
  183: 'Côtes de Toul',
  184: 'Côtes du Forez-AOVDQS',
  185: 'Côtes du Frontonnais',
  186: 'Côtes du Jura',
  187: 'Côtes du Marmandais',
  188: 'Côtes du Rhône',
  189: 'Côtes du Rhône Villages',
  190: 'Côtes du Rhône Villages Cairanne',
  191: 'Côtes du Rhône Villages Chusclan',
  192: 'Côtes du Rhône Villages Gadagne',
  193: 'Côtes du Rhône Villages Laudun',
  194: 'Côtes du Rhône Villages Massif d\'Uchaux',
  195: 'Côtes du Rhône Villages Plan de Dieu',
  196: 'Côtes du Rhône Villages Puyméras',
  197: 'Côtes du Rhône Villages Rasteau',
  198: 'Côtes du Rhône Villages Roaix',
  199: 'Côtes du Rhône Villages Rochegude',
  200: 'Côtes du Rhône Villages Rousset les vignes',
  201: 'Côtes du Rhône Villages Sablet',
  202: 'Côtes du Rhône Villages Saint-Gervais',
  203: 'Côtes du Rhône Villages Saint-Maurice',
  204: 'Côtes du Rhône Villages Saint-Pantaléon les vignes',
  205: 'Côtes du Rhône Villages Séguret',
  206: 'Côtes du Rhône Villages Signargues',
  207: 'Côtes du Rhône Villages Valréas',
  208: 'Côtes du Rhône Villages Visan',
  209: 'Côtes du Roussillon',
  210: 'Côtes du Roussillon Villages',
  211: 'Côtes du Vivarais',
  212: 'Cour-Cheverny',
  213: 'Crémant de Bordeaux',
  214: 'Crémant de Bourgogne',
  215: 'Crémant de Die',
  216: 'Crémant de Limoux',
  217: 'Crémant de Loire',
  218: 'Crémant du Jura',
  219: 'Crémant d\'Alsace',
  220: 'Crépy',
  221: 'Criots-Bâtard-Montrachet',
  222: 'Crozes-Hermitage',
  223: 'Echezeaux',
  224: 'Entraygues et Fel-AOVDQS',
  225: 'Entre-deux-Mers',
  226: 'Entre-deux-Mers-Haut-Benauge',
  227: 'Estaing-AOVDQS',
  228: 'Faugères',
  229: 'Fiefs Vendéens-AOVDQS',
  230: 'Fitou',
  231: 'Fixin',
  232: 'Fleurie',
  233: 'Floc de Gascogne',
  234: 'Francs Côtes de Bordeaux',
  235: 'Fronsac',
  236: 'Fronton',
  237: 'Gaillac',
  238: 'Gaillac premières côtes',
  239: 'Gevrey-Chambertin',
  240: 'Gigondas',
  241: 'Givry',
  242: 'Grands-Échezeaux',
  243: 'Graves',
  244: 'Graves de Vayres',
  245: 'Graves Supérieurs',
  246: 'Grignan les Adhémar',
  247: 'Griottes-Chambertin',
  248: 'Gros Plant du Pays Nantais-AOVDQS',
  249: 'Haut-Médoc',
  250: 'Haut-Montravel',
  251: 'Haut-Poitou-AOVDQS',
  252: 'Hermitage',
  253: 'Irancy',
  254: 'Irouléguy',
  255: 'Jasnières',
  256: 'Juliénas',
  257: 'Jurançon',
  258: 'Jurançon sec',
  259: 'L\'Etoile',
  260: 'La Grande Rue',
  261: 'La Tâche',
  262: 'Ladoix',
  263: 'Lalande de Pomerol',
  264: 'Languedoc',
  265: 'Languedoc-Grés de Montpellier',
  266: 'Languedoc-La Clape',
  267: 'Languedoc-Pézenas',
  268: 'Languedoc-Pic Saint Loup',
  269: 'Languedoc-Picpoul de Pinet',
  270: 'Languedoc-Terrasses de Béziers',
  271: 'Languedoc-Terrasses du Larzac',
  272: 'Languedoc-Terres de Sommières',
  273: 'Latricières-Chambertin',
  274: 'Lavilledieu-AOVDQS',
  275: 'Les Baux-de-Provence',
  276: 'Limoux',
  277: 'Lirac',
  278: 'Listrac-Médoc',
  279: 'Loupiac',
  280: 'Luberon',
  281: 'Lussac Saint-Émilion',
  282: 'Mâcon',
  283: 'Mâcon Supérieur',
  284: 'Mâcon-Villages',
  285: 'Macvin du Jura',
  286: 'Madiran',
  287: 'Malepère',
  288: 'Maranges',
  289: 'Marcillac',
  290: 'Margaux',
  291: 'Marsannay',
  292: 'Maury',
  293: 'Mazis-Chambertin',
  294: 'Mazoyères-Chambertin',
  295: 'Médoc',
  296: 'Menetou-Salon',
  297: 'Mercurey',
  298: 'Meursault',
  299: 'Minervois',
  300: 'Minervois-la-livinière',
  301: 'Monbazillac',
  302: 'Montagne Saint-Émilion',
  303: 'Montagny',
  304: 'Monthelie',
  305: 'Montlouis-sur-Loire',
  306: 'Montrachet',
  307: 'Montravel',
  308: 'Morey-Saint-Denis',
  309: 'Morgon',
  310: 'Moselle-AOVDQS',
  311: 'Moulin Ã  Vent',
  312: 'Moulis en Médoc',
  313: 'Muscadet',
  314: 'Muscadet Coteaux de la Loire',
  315: 'Muscadet Côtes de Grand-Lieu',
  316: 'Muscadet Sèvre-et-Maine',
  317: 'Muscat de Beaumes-de-Venise',
  318: 'Muscat de Frontignan',
  319: 'Muscat de Lunel',
  320: 'Muscat de Mireval',
  321: 'Muscat de Rivesaltes',
  322: 'Muscat de Saint Jean de Minervois',
  323: 'Muscat du Cap Corse',
  324: 'Musigny',
  325: 'Nuits-Saint-Georges',
  326: 'Orléans',
  327: 'Orléans-Cléry',
  328: 'Pacherenc du Vic-Bilh',
  329: 'Palette',
  330: 'Patrimonio',
  331: 'Pauillac',
  332: 'Pécharmant',
  333: 'Pernand-Vergelesses',
  334: 'Pessac-Léognan',
  335: 'Petit Chablis',
  336: 'Picpoul de Pinet',
  337: 'Pineau des Charentes',
  338: 'Pomerol',
  339: 'Pommard',
  340: 'Pouilly-Fuissé',
  341: 'Pouilly-Fumé',
  342: 'Pouilly-Loché',
  343: 'Pouilly-sur-Loire',
  344: 'Pouilly-Vinzelles',
  345: 'Premières Côtes de Blaye',
  346: 'Premières Côtes de Bordeaux',
  347: 'Puisseguin Saint-Émilion',
  348: 'Puligny-Montrachet',
  349: 'Quarts-de-Chaume',
  350: 'Quincy',
  351: 'Rasteau',
  352: 'Rasteau-vin doux naturel',
  353: 'Régnié',
  354: 'Reuilly',
  355: 'Richebourg',
  356: 'Rivesaltes',
  357: 'Romanée La,1)',
  358: 'Romanée Saint-Vivant',
  359: 'Romanée-Conti',
  360: 'Roséde Loire',
  361: 'Rosédes Riceys',
  362: 'Rosé d\'Anjou',
  363: 'Rosette',
  364: 'Roussette de Savoie',
  365: 'Roussette de Savoie Cru Frangy',
  366: 'Roussette de Savoie Cru Marestel',
  367: 'Roussette de Savoie Cru Monterminod',
  368: 'Roussette de Savoie Cru Monthoux',
  369: 'Roussette du Bugey',
  370: 'Ruchottes-Chambertin',
  371: 'Rully',
  372: 'Saint Sardos',
  373: 'Saint-Amour',
  374: 'Saint-Aubin',
  375: 'Saint-Bris',
  376: 'Saint-Chinian',
  377: 'Saint-Chinian Berlou',
  378: 'Saint-Chinian Roquebrun',
  379: 'Saint-Émilion',
  380: 'Saint-Émilion Grand Cru',
  381: 'Saint-Estèphe',
  382: 'Saint-Georges Saint-Émilion',
  383: 'Saint-Joseph',
  384: 'Saint-Julien',
  385: 'Saint-Mont',
  386: 'Saint-Nicolas-de-Bourgueil',
  387: 'Saint-Péray',
  388: 'Saint-Pourçain',
  389: 'Saint-Romain',
  390: 'Saint-Véran',
  391: 'Sainte-Croix-du-Mont',
  392: 'Sainte-Foy-Bordeaux',
  393: 'Sancerre',
  394: 'Santenay',
  395: 'Saumur',
  396: 'Saumur Brut',
  397: 'Saumur Puy-Notre-Dame',
  398: 'Saumur-Champigny',
  399: 'Saussignac',
  400: 'Sauternes',
  401: 'Savennières',
  402: 'Savennières Coulée-de-Serrant',
  403: 'Savennières Roche-aux-moines',
  404: 'Savigny-lès-Beaune',
  405: 'Seyssel',
  406: 'Tavel',
  407: 'Touraine',
  408: 'Touraine Noble-Joué',
  409: 'Touraine Sauvignon',
  410: 'Touraine-Amboise',
  411: 'Touraine-Azay-le-Rideau',
  412: 'Touraine-Mesland',
  413: 'Tursan-AOVDQS',
  414: 'Vacqueyras',
  415: 'Valencay AOVDQS',
  416: 'Ventoux',
  417: 'Vin de Savoie',
  418: 'Vin de Savoie Abymes',
  419: 'Vin de Savoie Apremont',
  420: 'Vin de Savoie Arbin',
  421: 'Vin de Savoie Ayze',
  422: 'Vin de Savoie Chautagne',
  423: 'Vin de Savoie Chignin',
  424: 'Vin de Savoie Chignin-Bergeron',
  425: 'Vin de Savoie Cruet',
  426: 'Vin de Savoie Jongieux',
  427: 'Vin de Savoie Marignan',
  428: 'Vin de Savoie Marin',
  429: 'Vin de Savoie Montmélian',
  430: 'Vin de Savoie Ripaille',
  431: 'Vin de Savoie Saint-Jean-de-la-Porte',
  432: 'Vin de Savoie Saint-Jeoire-Prieuré',
  433: 'Vinsobres',
  434: 'Viré-Clessé',
  435: 'Volnay',
  436: 'Volnay Santenots',
  437: 'Vosne-Romanée',
  438: 'Vougeot',
  439: 'Vouvray'
}
