export const SELECT_BOTTLE_TO_DELETE = 'SELECT_BOTTLE_TO_DELETE';
export const UNSELECT_BOTTLE_TO_DELETE = 'UNSELECT_BOTTLE_TO_DELETE';
export const SET_COUNT = 'SET_COUNT';
export const RESET_REMOVE_STATE = 'RESET_REMOVE_STATE';
export const SELECT_WINE_TO_REMOVE = 'SELECT_WINE_TO_REMOVE';
