# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install NPM client dependencies
        run: npm install --prefix client

      - name: Install NPM server dependencies
        run: npm install --prefix server

      - name: Install NPM scripts dependencies
        run: npm install --prefix scripts

      - name: Install NPM e2e dependencies
        run: npm install --prefix e2e

      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          sudo apt-get install -y graphicsmagick

      # Runs a single command using the runners shell
      - name: Run the app
        run: npm run start --prefix e2e

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: e2e
  server-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install NPM dependencies
        run: npm install --prefix server

      - name: Run the tests
        run: npm run test --prefix server
  server-linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install NPM dependencies
        run: npm install --prefix server

      - name: Run the linter
        run: npm run lint --prefix server
  client-linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install NPM dependencies
        run: npm install --prefix client

      - name: Run the linter
        run: npm run lint --prefix client

  deploy:
    runs-on: ubuntu-latest
    needs: [e2e, server-tests, server-linter, client-linter]
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v4

      - name: Install NPM client dependencies
        run: npm install --prefix client

      - name: Build client
        run: npm run build --prefix client

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Add remote host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$REMOTE_HOST" >> ~/.ssh/known_hosts
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}

      - name: Deploy to server
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_CLIENT_PATH: ${{ secrets.REMOTE_CLIENT_PATH }}
          REMOTE_SERVER_PATH: ${{ secrets.REMOTE_SERVER_PATH }}
        run: chmod +x deploy.sh && ./deploy.sh
