# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install NPM scripts dependencies
        run: npm install --prefix scripts

      - name: Install NPM e2e dependencies
        run: npm install --prefix e2e

      # Runs a single command using the runners shell
      - name: Run the app
        run: npm run start --prefix e2e

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: e2e
  server-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install NPM dependencies
        run: npm install

      - name: Run the tests
        run: npm run test:server
  server-linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install NPM dependencies
        run: npm install --prefix server

      - name: Run the linter
        run: npm run lint --prefix server
  client-linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install NPM dependencies
        run: npm install --prefix client

      - name: Run the linter
        run: npm run lint --prefix client
